apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-clusterscaler
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - meinetoonen.nl
    resources:
      - localnodes
    verbs:
      - "*"