apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-clusterscaler
spec:
  selector:
    matchLabels:
      app: local-clusterscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: local-clusterscaler
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      serviceAccountName: local-clusterscaler
      containers:
        - image: meinetoonen/local-clusterscaler:latest
          name: local-clusterscaler
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.2"
              memory: 200M
            requests:
              cpu: "0.1"
              memory: 100M
