kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-clusterscaler
subjects:
  - kind: ServiceAccount
    name: local-clusterscaler
    namespace: default
roleRef:
  kind: ClusterRole
  name: local-clusterscaler
  apiGroup: rbac.authorization.k8s.io