FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
WORKDIR /work/
EXPOSE 8080
RUN chown 1001 /work
RUN chmod "g+rwX" /work
RUN chown 1001:root /work

COPY src/main/docker/libsunec.so /work/library/
COPY --chown=1001:root target/*-runner /work/application
USER 1001
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
