apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localnodes.meinetoonen.nl
spec:
  group: meinetoonen.nl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ipAddress:
                  type: string
                name:
                  type: string
                type:
                  type: string
                cpu:
                  type: integer
                memory:
                  type: integer
            status:
              type: object
              properties:
                replicas:
                  type: integer
                labelSelector:
                  type: string
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
        # scale enables the scale subresource.

  scope: Namespaced
  names:
    plural: localnodes
    singular: localnode
    kind: LocalNode
    shortNames:
      - ln